manifestVersion: subsquid.io/v0.1
name: fearless-moonriver
version: 2
description: |-
  Parachain staking tracking
build:
deploy:
  secrets:
    - MOONRIVER_CHAIN_NODE
  addons:
    postgres:
  processor:
    cmd: ["node", "lib/chains/moonriver/processor"]
  api:
    cmd:
      [
        "npx",
        "squid-graphql-server",
        "--dumb-cache",
        "in-memory",
        "--dumb-cache-ttl",
        "1000",
        "--dumb-cache-size",
        "100",
        "--dumb-cache-max-age",
        "1000",
      ]
scale:
  processor:
    profile: medium
  addons:
    postgres:
      storage: 100Gi
  dedicated: true
